# Generated by Django 5.1.1 on 2024-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("gender", models.CharField(max_length=1)),
                ("type", models.CharField(max_length=60)),
                ("release_year", models.CharField(max_length=60)),
            ],
        ),
    ]
