# Generated by Django 5.1.1 on 2024-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_hero_image_alter_hero_name_alter_hero_release_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="release_year",
            field=models.IntegerField(max_length=4),
        ),
    ]
