# Generated by Django 5.1.1 on 2024-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_dailyhero"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhero",
            name="amount_of_people",
            field=models.IntegerField(default=0),
        ),
    ]
