# Generated by Django 5.1.1 on 2024-09-18 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.IntegerField()),
                ('image', models.ImageField(default='abilities/default.png', upload_to='abilities/')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hero')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('amount_of_people', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ability')),
            ],
        ),
    ]
