# Generated by Django 5.1.1 on 2024-09-21 16:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ability_dailyability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='guess_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ability',
            name='image',
            field=models.ImageField(default='abilities/default.jpg', upload_to=api.models.ability_image_path),
        ),
    ]
