# Generated by Django 5.1.1 on 2024-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hero_guess_attempts_alter_ability_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='guess_attempts',
            new_name='ability_guess_attempts',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_guess_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
