# Generated by Django 5.1.1 on 2024-09-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_guess_attempts_hero_ability_guess_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyability',
            name='amount_of_people',
        ),
        migrations.RemoveField(
            model_name='dailyhero',
            name='amount_of_people',
        ),
    ]
