# Generated by Django 5.1.1 on 2024-09-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_dailyability_amount_of_people_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='ability_guess_attempts',
            new_name='ability_guesses',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hero_guess_attempts',
            new_name='hero_guesses',
        ),
    ]
