# Generated by Django 5.1.1 on 2024-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_dailyhero_amount_of_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="image",
            field=models.ImageField(default="heroes/default.png", upload_to="heroes/"),
        ),
    ]
